Gen1PokemonMovesets = {
	"BULBASAUR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"GROWL",
						"LEECH SEED",
						"VINE WHIP",
						"POISON POWDER",
						"RAZOR LEAF",
						"GROWTH",
						"SLEEP POWDER",
						"SOLAR BEAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"IVYSAUR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"GROWL",
						"LEECH SEED",
						"VINE WHIP",
						"POISON POWDER",
						"RAZOR LEAF",
						"GROWTH",
						"SLEEP POWDER",
						"SOLAR BEAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"VENUSAUR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"GROWL",
						"LEECH SEED",
						"VINE WHIP",
						"POISON POWDER",
						"RAZOR LEAF",
						"GROWTH",
						"SLEEP POWDER",
						"SOLAR BEAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"CHARMANDER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"EMBER",
						"LEER",
						"RAGE",
						"SLASH",
						"FLAMETHROWER",
						"FIRE SPIN"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"SWORDS DANCE",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DRAGON RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"STRENGTH"]}},
	"CHARMELEON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"EMBER",
						"LEER",
						"RAGE",
						"SLASH",
						"FLAMETHROWER",
						"FIRE SPIN"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"SWORDS DANCE",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DRAGON RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"STRENGTH"]}},
	"CHARIZARD": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"EMBER",
						"LEER",
						"RAGE",
						"SLASH",
						"FLAMETHROWER",
						"FIRE SPIN"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"SWORDS DANCE",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DRAGON RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"FLY",
						"STRENGTH"]}},
	"SQUIRTLE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"TAIL WHIP",
						"BUBBLE",
						"WATER GUN",
						"BITE",
						"WITHDRAW",
						"SKULL BASH",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"WARTORTLE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"TAIL WHIP",
						"BUBBLE",
						"WATER GUN",
						"BITE",
						"WITHDRAW",
						"SKULL BASH",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"BLASTOISE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"TAIL WHIP",
						"BUBBLE",
						"WATER GUN",
						"BITE",
						"WITHDRAW",
						"SKULL BASH",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"CATERPIE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"STRING SHOT"],
					"MOVES BY TM/HM": [
						"NONE"]}},
	"METAPOD": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HARDEN"],
					"MOVES BY TM/HM": [
						"NONE"]}},
	"BUTTERFREE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"CONFUSION",
						"POISON POWDER",
						"STUN SPORE",
						"SLEEP POWDER",
						"SUPERSONIC",
						"WHIRLWIND",
						"PSYBEAM"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE"]}},
	"WEEDLE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POISON STING",
						"STRING SHOT"],
					"MOVES BY TM/HM": [
						"NONE"]}},
	"KAKUNA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HARDEN"],
					"MOVES BY TM/HM": [
						"NONE"]}},
	"BEEDRILL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"FURY ATTACK",
						"FOCUS ENERGY",
						"TWINEEDLE",
						"RAGE",
						"PIN MISSILE",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"PIDGEY": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"GUST",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"WHIRLWIND",
						"WING ATTACK",
						"AGILITY",
						"MIRROR MOVE"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"PIDGEOTTO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"GUST",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"WHIRLWIND",
						"WING ATTACK",
						"AGILITY",
						"MIRROR MOVE"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"PIDGEOT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"GUST",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"WHIRLWIND",
						"WING ATTACK",
						"AGILITY",
						"MIRROR MOVE"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"RATTATA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"TAIL WHIP",
						"QUICK ATTACK",
						"HYPER FANG",
						"FOCUS ENERGY",
						"SUPER FANG"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"BLIZZARD",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"RATICATE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"TAIL WHIP",
						"QUICK ATTACK",
						"HYPER FANG",
						"FOCUS ENERGY",
						"SUPER FANG"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"SPEAROW": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"GROWL",
						"LEER",
						"FURY ATTACK",
						"MIRROR MOVE",
						"DRILL PECK",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"FEAROW": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"GROWL",
						"LEER",
						"FURY ATTACK",
						"MIRROR MOVE",
						"DRILL PECK",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"EKANS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WRAP",
						"LEER",
						"POISON STING",
						"BITE",
						"GLARE",
						"SCREECH",
						"ACID"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"ARBOK": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WRAP",
						"LEER",
						"POISON STING",
						"BITE",
						"GLARE",
						"SCREECH",
						"ACID"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"PIKACHU": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"THUNDER SHOCK",
						"GROWL",
						"THUNDER WAVE",
						"QUICK ATTACK",
						"SWIFT",
						"AGILITY",
						"THUNDER"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"PAY DAY",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"FLASH"]}},
	"RAICHU": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"THUNDER SHOCK",
						"GROWL",
						"THUNDER WAVE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"FLASH"]}},
	"SANDSHREW": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"SAND-ATTACK",
						"SLASH",
						"POISON STING",
						"SWIFT",
						"FURY SWIPES"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"CUT",
						"STRENGTH"]}},
	"SANDSLASH": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"SAND-ATTACK",
						"SLASH",
						"POISON STING",
						"SWIFT",
						"FURY SWIPES"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"CUT",
						"STRENGTH"]}},
	"NIDORAN(F)": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"GROWL",
						"TACKLE",
						"SCRATCH",
						"POISON STING",
						"TAIL WHIP",
						"BITE",
						"FURY SWIPES",
						"DOUBLE KICK"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BLIZZARD",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"NIDORINA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"GROWL",
						"TACKLES",
						"SCRATCH",
						"POISON STING",
						"TAIL WHIP",
						"BITE",
						"FURY SWIPES",
						"DOUBLE KICK"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"NIDOQUEEN": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"BODY SLAM",
						"SCRATCH",
						"TAIL WHIP",
						"POISON STING"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"NIDORAN(M)": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LEER",
						"TACKLE",
						"HORN ATTACK",
						"POISON STING",
						"FOCUS ENERGY",
						"FURY ATTACK",
						"HORN DRILL",
						"DOUBLE KICK"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BLIZZARD",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"NIDORINO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LEER",
						"TACKLE",
						"HORN ATTACK",
						"POISON STING",
						"FOCUS ENERGY",
						"FURY ATTACK",
						"HORN DRILL",
						"DOUBLE KICK"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"NIDOKING": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"HORN ATTACK",
						"POISON STING",
						"THRASH"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"CLEFAIRY": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"GROWL",
						"SING",
						"DOUBLE SLAP",
						"MINIMIZE",
						"METRONOME",
						"DEFENSE CURL",
						"LIGHT SCREEN"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},
	"CLEFABLE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SING",
						"DOUBLE SLAP",
						"MINIMIZE",
						"METRONOME"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},
	"VULPIX": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"EMBER",
						"TAIL WHIP",
						"QUICK ATTACK",
						"ROAR",
						"CONFUSE RAY",
						"FLAMETHROWER",
						"FIRE SPIN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"NINETALES": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"EMBER",
						"TAIL WHIP",
						"QUICK ATTACK",
						"ROAR"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"JIGGLYPUFF": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SING",
						"POUND",
						"DISABLE",
						"DEFENSE CURL",
						"DOUBLE SLAP",
						"REST",
						"BODY SLAM",
						"DOUBLE-EDGE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},
	"WIGGLYTUFF": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SING",
						"DISABLE",
						"DEFENSE CURL",
						"DOUBLE SLAP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},
	"ZUBAT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LEECH LIFE",
						"SUPERSONIC",
						"BITE",
						"CONFUSE RAY",
						"WING ATTACK",
						"HAZE"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"REST",
						"SUBSTITUTE"]}},
	"GOLBAT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LEECH LIFE",
						"SCREECH",
						"BITE",
						"SUPERSONIC",
						"CONFUSE RAY",
						"WING ATTACK",
						"HAZE"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"REST",
						"SUBSTITUTE"]}},
	"ODDISH": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"ABSORB",
						"POISON POWDER",
						"STUN SPORE",
						"SLEEP POWDER",
						"ACID",
						"PETAL DANCE",
						"SOLAR BEAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"GLOOM": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"ABSORB",
						"POISON POWDER",
						"STUN SPORE",
						"SLEEP POWDER",
						"ACID",
						"PETAL DANCE",
						"SOLAR BEAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"VILEPLUME": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"STUN SPORE",
						"SLEEP POWDER",
						"ACID",
						"PETAL DANCE",
						"POISON POWDER"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"PARAS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"STUN SPORE",
						"LEECH LIFE",
						"SPORE",
						"SLASH",
						"GROWTH"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"PARASECT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"STUN SPORE",
						"LEECH LIFE",
						"SPORE",
						"SLASH",
						"GROWTH"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"VENONAT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"DISABLE",
						"POISON POWDER",
						"LEECH LIFE",
						"STUN SPORE",
						"PSYBEAM",
						"SLEEP POWDER",
						"PSYCHIC"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE"]}},
	"VENOMOTH": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"DISABLE",
						"POISON POWDER",
						"LEECH LIFE",
						"STUN SPORE",
						"PSYBEAM",
						"SLEEP POWDER",
						"PSYCHIC"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE"]}},
	"DIGLETT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"DIG",
						"SAND-ATTACK",
						"SLASH",
						"EARTHQUAKE"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE"]}},
	"DUGTRIO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"DIG",
						"SAND-ATTACK",
						"SLASH",
						"EARTHQUAKE"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE"]}},
	"MEOWTH": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"BITE",
						"PAY DAY",
						"SCREECH",
						"FURY SWIPES",
						"SLASH"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"PAY DAY",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"PERSIAN": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"GROWL",
						"BITE",
						"SCREECH",
						"PAY DAY",
						"FURY SWIPES",
						"SLASH"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"HYPER BEAM",
						"PAY DAY",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"PSYDUCK": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"TAIL WHIP",
						"DISABLE",
						"CONFUSION",
						"FURY SWIPES",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"GOLDUCK": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"TAIL WHIP",
						"DISABLE",
						"CONFUSION",
						"FURY SWIPES",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"MANKEY": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"LEER",
						"KARATE CHOP",
						"FURY SWIPES",
						"FOCUS ENERGY",
						"SEISMIC TOSS",
						"THRASH"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"PRIMEAPE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"LEER",
						"KARATE CHOP",
						"FURY SWIPES",
						"FOCUS ENERGY",
						"SEISMIC TOSS",
						"THRASH"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"GROWLITHE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BITE",
						"ROAR",
						"EMBER",
						"LEER",
						"TAKE DOWN",
						"AGILITY",
						"FLAMETHROWER"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"DRAGON RAGE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"ARCANINE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"ROAR",
						"EMBER",
						"LEER",
						"TAKE DOWN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"DRAGON RAGE",
						"DIG",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"POLIWAG": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BUBBLE",
						"HYPNOSIS",
						"WATER GUN",
						"DOUBLE SLAP",
						"BODY SLAM",
						"AMNESIA",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE",
						"SURF"]}},
	"POLIWHIRL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BUBBLE",
						"HYPNOSIS",
						"WATER GUN",
						"DOUBLE SLAP",
						"BODY SLAM",
						"AMNESIA",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"POLIWRATH": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HYPNOSIS",
						"WATER GUN",
						"DOUBLE SLAP",
						"BODY SLAM"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"ABRA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TELEPORT"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLASH"]}},
	"KADABRA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TELEPORT",
						"CONFUSION",
						"DISABLE",
						"PSYBEAM",
						"RECOVER",
						"PSYCHIC",
						"REFLECT"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DIG",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLASH"]}},
	"ALAKAZAM": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TELEPORT",
						"CONFUSION",
						"DISABLE",
						"PSYBEAM",
						"RECOVER",
						"PSYCHIC",
						"REFLECT"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"DIG",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLASH"]}},
	"MACHOP": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"KARATE CHOP",
						"LOW KICK",
						"LEER",
						"FOCUS ENERGY",
						"SEISMIC TOSS",
						"SUBMISSION"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"MACHOKE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"KARATE CHOP",
						"LOW KICK",
						"LEER",
						"FOCUS ENERGY",
						"SEISMIC TOSS",
						"SUBMISSION"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"MACHAMP": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"KARATE CHOP",
						"LOW KICK",
						"LEER",
						"FOCUS ENERGY",
						"SEISMIC TOSS",
						"SUBMISSION"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"BELLSPROUT": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"VINE WHIP",
						"GROWTH",
						"WRAP",
						"POISON POWDER",
						"SLEEP POWDER",
						"STUN SPORE",
						"ACID",
						"RAZOR LEAF",
						"SLAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"WEEPINBELL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"VINE WHIP",
						"GROWTH",
						"WRAP",
						"POISON POWDER",
						"SLEEP POWDER",
						"STUN SPORE",
						"ACID",
						"RAZOR LEAF",
						"SLAM"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"VICTREEBEL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SLEEP POWDER",
						"STUN SPORE",
						"ACID",
						"RAZOR LEAF",
						"WRAP",
						"POISON POWDER"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"TENTACOOL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"ACID",
						"SUPERSONIC",
						"WRAP",
						"POISON STING",
						"WATER GUN",
						"CONSTRICT",
						"BARRIER",
						"SCREECH",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"MEGA DRAIN",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"SURF"]}},
	"TENTACRUEL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"ACID",
						"SUPERSONIC",
						"WRAP",
						"POISON STING",
						"WATER GUN",
						"CONSTRICT",
						"BARRIER",
						"SCREECH",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"SURF"]}},
	"GEODUDE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"DEFENSE CURL",
						"ROCK THROW",
						"SELF-DESTRUCT",
						"HARDEN",
						"EARTHQUAKE",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"GRAVELER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"DEFENSE CURL",
						"ROCK THROW",
						"SELF-DESTRUCT",
						"HARDEN",
						"EARTHQUAKE",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"GOLEM": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"DEFENSE CURL",
						"ROCK THROW",
						"SELF-DESTRUCT",
						"HARDEN",
						"EARTHQUAKE",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"PONYTA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"EMBER",
						"TAIL WHIP",
						"STOMP",
						"GROWL",
						"FIRE SPIN",
						"TAKE DOWN",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"RAPIDASH": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"EMBER",
						"TAIL WHIP",
						"STOMP",
						"GROWL",
						"FIRE SPIN",
						"TAKE DOWN",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"SLOWPOKE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"CONFUSION",
						"DISABLE",
						"HEADBUTT",
						"GROWL",
						"WATER GUN",
						"AMNESIA",
						"PSYCHIC"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"PAY DAY",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH",
						"FLASH"]}},
	"SLOWBRO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"CONFUSION",
						"DISABLE",
						"HEADBUTT",
						"GROWL",
						"WATER GUN",
						"WITHDRAW",
						"AMNESIA",
						"PSYCHIC"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH",
						"FLASH"]}},
	"MAGNEMITE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SONIC BOOM",
						"THUNDER SHOCK",
						"SUPERSONIC",
						"THUNDER WAVE",
						"SWIFT",
						"SCREECH"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"FLASH"]}},
	"MAGNETON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SONIC BOOM",
						"THUNDER SHOCK",
						"SUPERSONIC",
						"THUNDER WAVE",
						"SWIFT",
						"SCREECH"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"FLASH"]}},
	"FARFETCH'D": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"SAND-ATTACK",
						"LEER",
						"FURY ATTACK",
						"SWORDS DANCE",
						"AGILITY",
						"SLASH"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"SWORDS DANCE",
						"WHIRLWIND",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"FLY"]}},
	"DODUO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"GROWL",
						"FURY ATTACK",
						"DRILL PECK",
						"RAGE",
						"TRI ATTACK",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"WHIRLWIND",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"SKY ATTACK",
						"REST",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLY"]}},
	"DODRIO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"GROWL",
						"FURY ATTACK",
						"DRILL PECK",
						"RAGE",
						"TRI ATTACK",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"WHIRLWIND",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"SKY ATTACK",
						"REST",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLY"]}},
	"SEEL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HEADBUTT",
						"GROWL",
						"AURORA BEAM",
						"REST",
						"TAKE DOWN",
						"ICE BEAM"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"PAY DAY",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"DEWGONG": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HEADBUTT",
						"GROWL",
						"AURORA BEAM",
						"REST",
						"TAKE DOWN",
						"ICE BEAM"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"GRIMER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"DISABLE",
						"POISON GAS",
						"MINIMIZE",
						"SLUDGE",
						"HARDEN",
						"SCREECH",
						"ACID ARMOR"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"RAGE",
						"MEGA DRAIN",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"MUK": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"DISABLE",
						"POISON GAS",
						"MINIMIZE",
						"SLUDGE",
						"HARDEN",
						"SCREECH",
						"ACID ARMOR"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"SHELLDER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"WITHDRAW",
						"SUPERSONIC",
						"CLAMP",
						"AURORA BEAM",
						"LEER",
						"ICE BEAM"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SELF-DESTRUCT",
						"SWIFT",
						"REST",
						"EXPLOSION",
						"TRI ATTACK",
						"SUBSTITUTE",
						"SURF"]}},
	"CLOYSTER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WITHDRAW",
						"SUPERSONIC",
						"CLAMP",
						"AURORA BEAM",
						"SPIKE CANNON"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SELF-DESTRUCT",
						"SWIFT",
						"REST",
						"EXPLOSION",
						"TRI ATTACK",
						"SUBSTITUTE",
						"SURF"]}},
	"GASTLY": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LICK",
						"CONFUSE RAY",
						"NIGHT SHADE",
						"HYPNOSIS",
						"DREAM EATER"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"RAGE",
						"MEGA DRAIN",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"DREAM EATER",
						"REST",
						"PSYWAVE",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"HAUNTER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LICK",
						"CONFUSE RAY",
						"NIGHT SHADE",
						"HYPNOSIS",
						"DREAM EATER"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"RAGE",
						"MEGA DRAIN",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"DREAM EATER",
						"REST",
						"PSYWAVE",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"GENGAR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"LICK",
						"CONFUSE RAY",
						"NIGHT SHADE",
						"HYPNOSIS",
						"DREAM EATER"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"MEGA DRAIN",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"SKULL BASH",
						"DREAM EATER",
						"REST",
						"PSYWAVE",
						"EXPLOSION",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"ONIX": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SCREECH",
						"BIND",
						"ROCK THROW",
						"RAGE",
						"SLAM",
						"HARDEN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"REST",
						"EXPLOSION",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"DROWZEE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"HYPNOSIS",
						"DISABLE",
						"CONFUSION",
						"HEADBUTT",
						"POISON GAS",
						"PSYCHIC",
						"MEDITATE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"DREAM EATER",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLASH"]}},
	"HYPNO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"HYPNOSIS",
						"DISABLE",
						"CONFUSION",
						"HEADBUTT",
						"POISON GAS",
						"PSYCHIC",
						"MEDITATE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"DREAM EATER",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLASH"]}},
	"KRABBY": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BUBBLE",
						"LEER",
						"VICE GRIP",
						"GUILLOTINE",
						"STOMP",
						"CRABHAMMER",
						"HARDEN"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"SURF",
						"STRENGTH"]}},
	"KINGLER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BUBBLE",
						"LEER",
						"VICE GRIP",
						"GUILLOTINE",
						"STOMP",
						"CRABHAMMER",
						"HARDEN"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"SURF",
						"STRENGTH"]}},
	"VOLTORB": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SCREECH",
						"SONIC BOOM",
						"SELF-DESTRUCT",
						"LIGHT SCREEN",
						"SWIFT",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"THUNDERBOLT",
						"THUNDER",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SELF-DESTRUCT",
						"SWIFT",
						"REST",
						"THUNDER WAVE",
						"EXPLOSION",
						"SUBSTITUTE",
						"FLASH"]}},
	"ELECTRODE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SCREECH",
						"SONIC BOOM",
						"SELF-DESTRUCT",
						"LIGHT SCREEN",
						"SWIFT",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"HYPER BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SELF-DESTRUCT",
						"SWIFT",
						"REST",
						"THUNDER WAVE",
						"EXPLOSION",
						"SUBSTITUTE",
						"FLASH"]}},
	"EXEGGCUTE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BARRAGE",
						"HYPNOSIS",
						"REFLECT",
						"LEECH SEED",
						"STUN SPORE",
						"POISON POWDER",
						"SOLAR BEAM",
						"SLEEP POWDER"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SELF-DESTRUCT",
						"EGG BOMB",
						"REST",
						"PSYWAVE",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"EXEGGUTOR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BARRAGE",
						"HYPNOSIS",
						"STOMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SELF-DESTRUCT",
						"EGG BOMB",
						"REST",
						"PSYWAVE",
						"EXPLOSION",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"CUBONE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BONE CLUB",
						"GROWL",
						"LEER",
						"FOCUS ENERGY",
						"THRASH",
						"BONEMERANG",
						"RAGE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"MAROWAK": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BONE CLUB",
						"GROWL",
						"LEER",
						"FOCUS ENERGY",
						"THRASH",
						"BONEMERANG",
						"RAGE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"HITMONLEE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"DOUBLE KICK",
						"MEDITATE",
						"ROLLING KICK",
						"JUMP KICK",
						"FOCUS ENERGY",
						"HI JUMP KICK",
						"MEGA KICK"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"HITMONCHAN": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"COMET PUNCH",
						"AGILITY",
						"FIRE PUNCH",
						"ICE PUNCH",
						"THUNDER PUNCH",
						"MEGA PUNCH",
						"COUNTER"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"LICKITUNG": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WRAP",
						"SUPERSONIC",
						"STOMP",
						"DISABLE",
						"DEFENSE CURL",
						"SLAM",
						"SCREECH"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"SWORDS DANCE",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"SURF",
						"STRENGTH"]}},
	"KOFFING": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SMOG",
						"SLUDGE",
						"SMOKESCREEN",
						"SELF-DESTRUCT",
						"HAZE",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"WEEZING": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SMOG",
						"SLUDGE",
						"SMOKESCREEN",
						"SELF-DESTRUCT",
						"HAZE",
						"EXPLOSION"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"REST",
						"EXPLOSION",
						"SUBSTITUTE"]}},
	"RHYHORN": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HORN ATTACK",
						"STOMP",
						"TAIL WHIP",
						"FURY ATTACK",
						"HORN DRILL",
						"LEER",
						"TAKE DOWN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"RHYDON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HORN ATTACK",
						"STOMP",
						"TAIL WHIP",
						"FURY ATTACK",
						"HORN DRILL",
						"LEER",
						"TAKE DOWN"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"CHANSEY": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"DOUBLE SLAP",
						"SING",
						"GROWL",
						"MINIMIZE",
						"DEFENSE CURL",
						"LIGHT SCREEN",
						"DOUBLE-EDGE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"EGG BOMB",
						"FIRE BLAST",
						"SKULL BASH",
						"SOFT-BOILED",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},
	"TANGELA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"CONSTRICT",
						"BIND",
						"ABSORB",
						"POISON POWDER",
						"STUN SPORE",
						"SLEEP POWDER",
						"SLAM",
						"GROWTH"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"KANGASKHAN": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"COMET PUNCH",
						"RAGE",
						"BITE",
						"TAIL WHIP",
						"MEGA PUNCH",
						"LEER",
						"DIZZY PUNCH"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"HORSEA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BUBBLE",
						"SMOKESCREEN",
						"LEER",
						"WATER GUN",
						"AGILITY",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"SEADRA": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BUBBLE",
						"SMOKESCREEN",
						"LEER",
						"WATER GUN",
						"AGILITY",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"GOLDEEN": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"TAIL WHIP",
						"SUPERSONIC",
						"HORN ATTACK",
						"FURY ATTACK",
						"WATERFALL",
						"HORN DRILL",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"SEAKING": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"TAIL WHIP",
						"SUPERSONIC",
						"HORN ATTACK",
						"FURY ATTACK",
						"WATERFALL",
						"HORN DRILL",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"STARYU": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"WATER GUN",
						"HARDEN",
						"RECOVER",
						"SWIFT",
						"MINIMIZE",
						"LIGHT SCREEN",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"SURF",
						"FLASH"]}},
	"STARMIE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"WATER GUN",
						"HARDEN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"SURF",
						"FLASH"]}},
	"MR. MIME": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"CONFUSION",
						"BARRIER",
						"LIGHT SCREEN",
						"DOUBLE SLAP",
						"MEDITATE",
						"SUBSTITUTE"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"THUNDER WAVE",
						"PSYWAVE",
						"SUBSTITUTE",
						"FLASH"]}},
	"SCYTHER": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"QUICK ATTACK",
						"LEER",
						"FOCUS ENERGY",
						"DOUBLE TEAM",
						"SLASH",
						"SWORDS DANCE",
						"AGILITY"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT"]}},
	"JYNX": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"LOVELY KISS",
						"LICK",
						"DOUBLE SLAP",
						"ICE PUNCH",
						"BODY SLAM",
						"THRASH",
						"BLIZZARD"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE"]}},
	"ELECTABUZZ": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"QUICK ATTACK",
						"LEER",
						"THUNDER SHOCK",
						"SCREECH",
						"THUNDER PUNCH",
						"LIGHT SCREEN",
						"THUNDER"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},
	"MAGMAR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"EMBER",
						"LEER",
						"CONFUSE RAY",
						"FIRE PUNCH",
						"SMOKESCREEN",
						"SMOG",
						"FLAMETHROWER"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"METRONOME",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"PINSIR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"VICE GRIP",
						"SEISMIC TOSS",
						"GUILLOTINE",
						"FOCUS ENERGY",
						"HARDEN",
						"SLASH",
						"SWORDS DANCE"],
					"MOVES BY TM/HM": [
						"SWORDS DANCE",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"STRENGTH"]}},
	"TAUROS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"STOMP",
						"TAIL WHIP",
						"LEER",
						"RAGE",
						"TAKE DOWN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"MIMIC",
						"DOUBLE TEAM",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"STRENGTH"]}},
	"MAGIKARP": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SPLASH",
						"TACKLE"],
					"MOVES BY TM/HM": [
						"NONE"]}},
	"GYARADOS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"BITE",
						"DRAGON RAGE",
						"LEER",
						"HYDRO PUMP",
						"HYPER BEAM"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"DRAGON RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"LAPRAS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WATER GUN",
						"GROWL",
						"SING",
						"MIST",
						"BODY SLAM",
						"CONFUSE RAY",
						"ICE BEAM",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"SOLAR BEAM",
						"DRAGON RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"DITTO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TRANSFORM"],
					"MOVES BY TM/HM": [
						"NONE"]}},
	"EEVEE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"TAIL WHIP",
						"BITE",
						"TAKE DOWN"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"VAPOREON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"WATER GUN",
						"TAIL WHIP",
						"BITE",
						"ACID ARMOR",
						"HAZE",
						"MIST",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"JOLTEON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"THUNDER SHOCK",
						"TAIL WHIP",
						"THUNDER WAVE",
						"DOUBLE KICK",
						"AGILITY",
						"PIN MISSILE",
						"THUNDER"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"FLASH"]}},
	"FLAREON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SAND-ATTACK",
						"QUICK ATTACK",
						"EMBER",
						"TAIL WHIP",
						"BITE",
						"LEER",
						"FIRE SPIN",
						"RAGE",
						"FLAMETHROWER"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE"]}},
	"PORYGON": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"TACKLE",
						"SHARPEN",
						"CONVERSION",
						"PSYBEAM",
						"RECOVER",
						"AGILITY",
						"TRI ATTACK"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"FLASH"]}},
	"OMANYTE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WATER GUN",
						"WITHDRAW",
						"HORN ATTACK",
						"LEER",
						"SPIKE CANNON",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"OMASTAR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WATER GUN",
						"WITHDRAW",
						"HORN ATTACK",
						"LEER",
						"SPIKE CANNON",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"KABUTO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"HARDEN",
						"ABSORB",
						"SLASH",
						"LEER",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"REST",
						"SUBSTITUTE",
						"SURF"]}},
	"KABUTOPS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"SCRATCH",
						"HARDEN",
						"ABSORB",
						"SLASH",
						"LEER",
						"HYDRO PUMP"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"SWORDS DANCE",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"SUBMISSION",
						"SEISMIC TOSS",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SKULL BASH",
						"REST",
						"SUBSTITUTE",
						"CUT",
						"SURF"]}},
	"AERODACTYL": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WING ATTACK",
						"AGILITY",
						"SUPERSONIC",
						"BITE",
						"TAKE DOWN",
						"HYPER BEAM"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"DRAGON RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"SNORLAX": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"HEADBUTT",
						"AMNESIA",
						"REST",
						"BODY SLAM",
						"HARDEN",
						"DOUBLE-EDGE",
						"HYPER BEAM"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"PSYCHIC",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"PSYWAVE",
						"ROCK SLIDE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"ARTICUNO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"ICE BEAM",
						"BLIZZARD",
						"AGILITY",
						"MIST"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"ZAPDOS": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"THUNDER SHOCK",
						"DRILL PECK",
						"THUNDER",
						"AGILITY",
						"LIGHT SCREEN"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"WHIRLWIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"FLY",
						"FLASH"]}},
	"MOLTRES": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"PECK",
						"FIRE SPIN",
						"LEER",
						"AGILITY",
						"SKY ATTACK"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"TOXIC",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"HYPER BEAM",
						"RAGE",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKY ATTACK",
						"REST",
						"SUBSTITUTE",
						"FLY"]}},
	"DRATINI": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WRAP",
						"LEER",
						"THUNDER WAVE",
						"AGILITY",
						"SLAM",
						"DRAGON RAGE",
						"HYPER BEAM"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"DRAGON RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"SURF"]}},
	"DRAGONAIR": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WRAP",
						"LEER",
						"THUNDER WAVE",
						"AGILITY",
						"SLAM",
						"DRAGON RAGE",
						"HYPER BEAM"],
					"MOVES BY TM/HM": [
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"RAGE",
						"DRAGON RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"SURF"]}},
	"DRAGONITE": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"WRAP",
						"THUNDER WAVE",
						"LEER",
						"AGILITY",
						"SLAM",
						"DRAGON RAGE",
						"HYPER BEAM"],
					"MOVES BY TM/HM": [
						"RAZOR WIND",
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"RAGE",
						"DRAGON RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"SUBSTITUTE",
						"SURF",
						"STRENGTH"]}},
	"MEWTWO": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"CONFUSION",
						"DISABLE",
						"SWIFT",
						"PSYCHIC",
						"BARRIER",
						"RECOVER",
						"MIST",
						"AMNESIA"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"MEGA KICK",
						"TOXIC",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"SOLAR BEAM",
						"THUNDERBOLT",
						"THUNDER",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"FIRE BLAST",
						"SKULL BASH",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"STRENGTH",
						"FLASH"]}},	"MEW": {
				"MOVESET": {
					"MOVES BY LEVEL": [
						"POUND",
						"TRANSFORM",
						"MEGA PUNCH",
						"METRONOME",
						"PSYCHIC"],
					"MOVES BY TM/HM": [
						"MEGA PUNCH",
						"RAZOR WIND",
						"SWORDS DANCE",
						"WHIRLWIND",
						"MEGA KICK",
						"TOXIC",
						"HORN DRILL",
						"BODY SLAM",
						"TAKE DOWN",
						"DOUBLE-EDGE",
						"BUBBLE BEAM",
						"WATER GUN",
						"ICE BEAM",
						"BLIZZARD",
						"HYPER BEAM",
						"PAY DAY",
						"SUBMISSION",
						"COUNTER",
						"SEISMIC TOSS",
						"RAGE",
						"MEGA DRAIN",
						"SOLAR BEAM",
						"DRAGON RAGE",
						"THUNDERBOLT",
						"THUNDER",
						"EARTHQUAKE",
						"FISSURE",
						"DIG",
						"PSYCHIC",
						"TELEPORT",
						"MIMIC",
						"DOUBLE TEAM",
						"REFLECT",
						"BIDE",
						"METRONOME",
						"SELF-DESTRUCT",
						"EGG BOMB",
						"FIRE BLAST",
						"SWIFT",
						"SKULL BASH",
						"SOFT-BOILED",
						"DREAM EATER",
						"SKY ATTACK",
						"REST",
						"THUNDER WAVE",
						"PSYWAVE",
						"EXPLOSION",
						"ROCK SLIDE",
						"TRI ATTACK",
						"SUBSTITUTE",
						"CUT",
						"FLY",
						"SURF",
						"STRENGTH",
						"FLASH"]}}}